pipeline:
    stages:
        - stage:
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          namespace: harness-build
                          connectorRef: account.HarnessPOC
                  execution:
                      steps:
                          - step:
                                type: RunTests
                                spec:
                                    runOnlySelectedTests: true
                                    resources:
                                        limits:
                                            memory: 2Gi
                                            cpu: "1"
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - "**/*.xml"
                                    language: Java
                                    image: 3.8.4-jdk-11
                                    connectorRef: account.harnessImage
                                    buildTool: Maven
                                    args: test
                                name: Run tests
                                identifier: Run_tests
                  cloneCodebase: true
              name: Build
              identifier: Build
    properties:
        ci:
            codebase:
                repoName: sonar-java
                connectorRef: account.HarnessSonarsourcePOC
                build: <+input>
    projectIdentifier: SonarJava
    orgIdentifier: default
    name: DavPipeline
    identifier: DavPipeline
    allowStageExecutions: false
