pipeline:
    stages:
        - stage:
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          namespace: harness-build
                          connectorRef: account.HarnessPOC
                  execution:
                      steps:
                          - step:
                                type: RestoreCacheS3
                                name: MavenRestoreCache
                                identifier: MavenRestoreCache
                                spec:
                                    connectorRef: account.HarnessAWSPOC
                                    region: eu-central-1
                                    bucket: sonarsource-harness-poc
                                    key: sonar-java-maven
                                    archiveFormat: Tar
                                    failIfKeyNotFound: false
                                failureStrategies:
                                    - onFailure:
                                          errors:
                                              - Timeout
                                              - Unknown
                                          action:
                                              type: MarkAsSuccess
                          - step:
                                type: RunTests
                                spec:
                                    connectorRef: account.harnessImage
                                    image: maven:3.8.4-openjdk-17
                                    language: Java
                                    buildTool: Maven
                                    args: test
                                    runOnlySelectedTests: true
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - "**/*.xml"
                                    resources:
                                        limits:
                                            memory: 2Gi
                                            cpu: "1"
                                name: Run tests
                                identifier: Run_tests
                          - step:
                                type: SaveCacheS3
                                name: MavenCache
                                identifier: MavenCache
                                spec:
                                    connectorRef: account.HarnessAWSPOC
                                    region: eu-central-1
                                    bucket: sonarsource-harness-poc
                                    key: sonar-java-maven
                                    sourcePaths:
                                        - .m2/repository
                                    archiveFormat: Tar
                                    override: true
                  cloneCodebase: true
              name: Build
              identifier: Build
    properties:
        ci:
            codebase:
                repoName: sonar-java
                connectorRef: account.HarnessSonarsourcePOC
                build: <+input>
    projectIdentifier: SonarJava
    orgIdentifier: default
    name: DavPipeline
    identifier: DavPipeline
    allowStageExecutions: false
