pipeline:
    stages:
        - stage:
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.HarnessPOC
                          namespace: harness-build
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Env
                                identifier: Env
                                spec:
                                    connectorRef: account.harnessImage
                                    image: bash
                                    command: |
                                        env
                          - step:
                                type: RestoreCacheS3
                                name: MavenRestoreCache
                                identifier: MavenRestoreCache
                                spec:
                                    connectorRef: account.HarnessAWSPOC
                                    region: eu-central-1
                                    bucket: sonarsource-harness-poc
                                    key: static-value
                                    archiveFormat: Tar
                                    failIfKeyNotFound: false
                                failureStrategies:
                                    - onFailure:
                                          errors:
                                              - Timeout
                                              - Unknown
                                          action:
                                              type: MarkAsSuccess
                          - step:
                                type: RunTests
                                spec:
                                    connectorRef: account.harnessImage
                                    image: maven:3.8.4-openjdk-17
                                    language: Java
                                    buildTool: Maven
                                    args: test -DskipTests
                                    runOnlySelectedTests: true
                                    preCommand: |
                                        whoami
                                    postCommand: |
                                        whoami
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - "**/*.xml"
                                    resources:
                                        limits:
                                            memory: 2Gi
                                            cpu: "1"
                                name: Run tests
                                identifier: Run_tests
                          - step:
                                type: SaveCacheS3
                                name: MavenCache
                                identifier: MavenCache
                                spec:
                                    connectorRef: account.HarnessAWSPOC
                                    region: eu-central-1
                                    bucket: sonarsource-harness-poc
                                    key: static-value
                                    sourcePaths:
                                        - /root/.m2/repository
                                    archiveFormat: Tar
                                    override: true
                                failureStrategies:
                                    - onFailure:
                                          errors:
                                              - AllErrors
                                          action:
                                              type: MarkAsSuccess
                  cloneCodebase: true
                  sharedPaths:
                      - /root/.m2/repository
              name: Build
              identifier: Build
        - stage:
              name: IT
              identifier: IT
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      useFromStage: Build
                  serviceDependencies:
                      - identifier: mysql
                        name: mysql
                        type: Service
                        spec:
                            connectorRef: account.harnessImage
                            image: mysql:5
                            envVariables:
                                MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: CheckMySQL
                                identifier: CheckMySQL
                                spec:
                                    connectorRef: account.harnessImage
                                    image: bash
                                    command: wget http://localhost:3306
    properties:
        ci:
            codebase:
                repoName: sonar-java
                connectorRef: account.HarnessSonarsourcePOC
                build: <+input>
    projectIdentifier: SonarJava
    orgIdentifier: default
    name: DavPipeline
    identifier: DavPipeline
    allowStageExecutions: false
