template:
    name: ruling
    identifier: ruling
    versionLabel: Version1
    type: Step
    projectIdentifier: SonarJava
    orgIdentifier: default
    spec:
        type: RunTests
        spec:
            connectorRef: account.awsdev
            image: 501215020883.dkr.ecr.eu-central-1.amazonaws.com/harness-images-dev:latest
            language: Java
            buildTool: Maven
            args: package -Pit-ruling -Dsonar.runtimeVersion=LATEST_RELEASE[8.9] -Dmaven.test.redirectTestOutputToFile=false -B -e -V -Dparallel=methods -DuseUnlimitedThreads=true
            runOnlySelectedTests: true
            preCommand: |-
                harness-env QA
                source set_maven_build_version <+execution.steps.BUILD.output.outputVariables.BUILD_NUMBER>
                cd its/ruling
            reports:
                type: JUnit
                spec:
                    paths:
                        - "**/*.xml"
