pipeline:
    name: Test
    identifier: Test
    allowStageExecutions: false
    projectIdentifier: SonarJava
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: githubtom
                repoName: sonar-java
                build: <+input>
    stages:
        - stage:
              name: test
              identifier: test
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.k8sdev
                          namespace: harness-build
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test
                                identifier: test
                                spec:
                                    connectorRef: account.awsdev
                                    image: 501215020883.dkr.ecr.eu-central-1.amazonaws.com/harness-images-dev:latest
                                    command: |-
                                        which -a bash
                                        echo $0
                                        ps
                                        cat /etc/passwd
                                        git --version
                          - step:
                                type: Run
                                name: test2
                                identifier: test2
                                spec:
                                    connectorRef: account.awsdev
                                    image: 501215020883.dkr.ecr.eu-central-1.amazonaws.com/harness-images-dev:latest
                                    command: ". harness-env QA                "
                                    shell: Bash
