pipeline:
    name: TomPipeline
    identifier: TomPipeline
    allowStageExecutions: false
    projectIdentifier: SonarJava
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: account.HarnessSonarsourcePOC
                repoName: sonar-java
                build: <+input>
    stages:
        - stage:
              name: BUILD
              identifier: BUILD
              type: CI
              spec:
                  cloneCodebase: true
                  sharedPaths:
                      - /home/sonarsource/.m2
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.HarnessPOC
                          namespace: harness-build
                  execution:
                      steps:
                          - step:
                                type: RestoreCacheS3
                                name: MavenRestoreCache
                                identifier: MavenRestoreCache
                                spec:
                                    connectorRef: account.HarnessAWSPOC
                                    region: eu-central-1
                                    bucket: sonarsource-harness-poc
                                    key: m2-repos
                                    archiveFormat: Tar
                                    failIfKeyNotFound: false
                                failureStrategies:
                                    - onFailure:
                                          errors:
                                              - Timeout
                                              - Unknown
                                          action:
                                              type: MarkAsSuccess
                          - step:
                                type: Run
                                name: BUILD
                                identifier: BUILD
                                spec:
                                    connectorRef: account.HarnessAWSPOC
                                    image: 460386131003.dkr.ecr.eu-central-1.amazonaws.com/ci-images:latest
                                    command: |-
                                        ls -alr ~/.m2
                                        source harness-env
                                        echo "================== Dumping env vars ===============>"
                                        env
                                        echo "================ End of env vars dump =============>"
                                        regular_mvn_build_deploy_analyze \
                                        -Dsonar.projectKey=SonarSource-PoC-Hio_sonar-java \
                                        -Dsonar.organization=sonarsource-poc-hio \
                                        -DskipTests 
                                    envVariables:
                                        SONAR_HOST_URL: <+pipeline.variables.SONAR_HOST_URL>
                                        PROJECT: <+pipeline.variables.PROJECT>
                                        GITHUB_REPO: SonarSource-PoC-Hio/sonar-java
                                        SONAR_TOKEN: <+secrets.getValue("SONAR_TOKEN")>
                                        ARTIFACTORY_URL: https://repox.jfrog.io/repox
                                        ARTIFACTORY_DEPLOY_REPO: poc-harness-qa
                                        ARTIFACTORY_DEPLOY_USERNAME: <+secrets.getValue("account.ARTIFACTORY_DEPLOY_USERNAME")>
                                        ARTIFACTORY_DEPLOY_PASSWORD: <+secrets.getValue("account.ARTIFACTORY_DEPLOY_PASSWORD")>
                                        ARTIFACTORY_PRIVATE_USERNAME: <+secrets.getValue("account.ARTIFACTORY_PRIVATE_USERNAME")>
                                        ARTIFACTORY_PRIVATE_PASSWORD: <+secrets.getValue("account.ARTIFACTORY_PRIVATE_PASSWORD")>
                                    outputVariables:
                                        - name: BUILD_NUMBER
                                failureStrategies: []
                          - step:
                                type: SaveCacheS3
                                name: MavenCache
                                identifier: MavenCache
                                spec:
                                    connectorRef: account.HarnessAWSPOC
                                    region: eu-central-1
                                    bucket: sonarsource-harness-poc
                                    key: m2-repos
                                    sourcePaths:
                                        - /home/sonarsource/.m2
                                    archiveFormat: Tar
                                    override: true
                                failureStrategies:
                                    - onFailure:
                                          errors:
                                              - AllErrors
                                          action:
                                              type: MarkAsSuccess
                          - step:
                                type: Run
                                name: promote
                                identifier: promote
                                spec:
                                    connectorRef: account.harnessImage
                                    image: releases-docker.jfrog.io/jfrog/jfrog-cli-v2-jf
                                    command: |-
                                        export BUILD_NUMBER=<+execution.steps.BUILD.output.outputVariables.BUILD_NUMBER>
                                        echo $BUILD_NUMBER
                                        jf config import $REPOX_PROMOTER_CONFIG
                                        jf rt bpr --status 'it-passed' <+pipeline.variables.PROJECT> $BUILD_NUMBER poc-harness-builds
                                    envVariables:
                                        REPOX_PROMOTER_CONFIG: <+secrets.getValue("account.REPOX_PROMOTER_CONFIG")>
    variables:
        - name: GITHUB_REPO
          type: String
          value: SonarSource-PoC-Hio/sonar-java
        - name: PROJECT
          type: String
          value: sonar-java
        - name: SONAR_HOST_URL
          type: String
          value: https://sonarcloud.io
