pipeline:
    name: TomPipeline
    identifier: TomPipeline
    allowStageExecutions: false
    projectIdentifier: SonarJava
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: account.HarnessSonarsourcePOC
                repoName: sonar-java
                build: <+input>
    stages:
        - stage:
              name: build
              identifier: build
              type: CI
              spec:
                  cloneCodebase: true
                  sharedPaths:
                      - /build
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.HarnessPOC
                          namespace: harness-build
                  execution:
                      steps:
                          - step:
                                type: RunTests
                                name: run tests
                                identifier: run_tests
                                spec:
                                    connectorRef: account.HarnessAWSPOC
                                    image: http://460386131003.dkr.ecr.eu-central-1.amazonaws.com/ci-images:latest
                                    language: Java
                                    buildTool: Maven
                                    args: test -DskipTests
                                    runOnlySelectedTests: false
                                    resources:
                                        limits:
                                            memory: 2Gi
                                            cpu: "1"
                                failureStrategies: []
